### ISSUE TITLE
Changing the date format

### ISSUE THREAD

**Issue by bilelomrani1** [semantic-release/release-notes-generator#187]
I wanted to change the date format, next to each release. The default format is `yyyy-mm-dd`. I looked at [conventional-changelog-writer properties](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#options) and saw that there is a `transform` method that formats `committerDate` with `yyyy-mm-dd`. But because it's a function, I don't really know how am I supposed to hook into it from my `.releaserc` file.

Looking at the source code of `conventional-changelog-writer`, the default `transform` method is
```javascript
options.transform = _.assign({
      hash: function (hash) {
        if (_.isString(hash)) {
          return hash.substring(0, 7)
        }
      },
      header: function (header) {
        return header.substring(0, 100)
      },
      committerDate: function (date) {
        if (!date) {
          return
        }

        return dateFormat(date, 'yyyy-mm-dd', true)
      }
    }, options.transform)
```
I tried the following but it fails.
```yaml
branches:
  - master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      writerOpts:
        date: dateFormat(new Date(), 'yyyy/mm/dd', true)
        transform: |
          _.assign({
            hash: function (hash) {
              if (_.isString(hash)) {
                return hash.substring(0, 7)
              }
            },
            header: function (header) {
              return header.substring(0, 100)
            },
            committerDate: function (date) {
              if (!date) {
                return
              }

              return dateFormat(date, 'yyyy/mm/dd', true)
            }
          }, options.transform)
```
