### ISSUE TITLE
question: link to both GH PR numbers and external issues

### ISSUE THREAD

**Issue by wyardley** [semantic-release/release-notes-generator#391]
I have the following config

```yaml
  - path: '@semantic-release/release-notes-generator'
    preset: conventionalcommits
    presetConfig:
      issuePrefixes:
        - 'FOO-'
        - 'BAR-'
      issueUrlFormat: 'https://linear.app/xyz/issue/{{prefix}}{{id}}'
```

which works great. However, that means that where before I'd have the changelog link for the GH PR #
```
* do something (FOO-775) ([#779](https://github.com/xyz/somerepo/issues/779)) ([f885465](https://github.com/xyz/somerepo/commit/f88546534c2d6650674e522bd2e0d3aeca26586a))
```

Now I have the link to the issue within our issue tracking system (Linear, in this case), and the commit, but not to the PR #:
```
* do something ([FOO-775](https://linear.app/xyz/issue/FOO-775)) (#779) ([f885465](https://github.com/xyz/somerepo/commit/f88546534c2d6650674e522bd2e0d3aeca26586a))
```

Is there a way to keep issue / PR #s from GH working while also linking to our issues as well (for example, can I have two different configs for the issue prefixes / url format)?

Also, is there an easy way to regenerate / backfill existing items after changing the config?
